FROM python:3

WORKDIR /usr/src/app

COPY requirements-nonjson-to-ecs.txt ./
RUN pip install --no-cache-dir -r requirements-nonjson-to-ecs.txt

COPY . .

CMD [ "python", "./logger-nonjson-to-ecs.py" ]
